name: my_simple_note
description: A simple notes application using Flutter and SQLite.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.0.0+3
  path_provider: ^2.0.11
  path: ^1.9.0
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  async: 2.11.0
  boolean_selector: 2.1.1
  characters: 1.3.0
  clock: 1.1.1
  collection: 1.18.0
  fake_async: 1.3.1
  flutter_lints: ^5.0.0
  leak_tracker: 10.0.5
  leak_tracker_flutter_testing: 3.0.5
  lints: ^5.0.0
  matcher: 0.12.16+1
  material_color_utilities: 0.11.1
  meta: 1.15.0
  stack_trace: 1.11.1
  string_scanner: 1.2.0
  test_api: 0.7.2
  vm_service: 14.2.5

flutter_icons:
  android: true
  ios: true
  image_path: "D:/icons/icon.png"

flutter:
  assets:
    - assets/background.png
